language: node_js
node_js:
  - "0.11"
  - "0.10"
  - iojs
  - iojs-v1.0.2
script:
  - node --stack-trace-limit=1000 --allow-natives-syntax unittests.js
  - node --stack-trace-limit=1000 --allow-natives-syntax servertests.js
env: IMPRESS_MODE=test
